module.exports = {
    name: 'MealService',
    func: function ($http) {

        const availableMeals = [];

        return {

            postMeal() {

                const servings = document.getElementById('servings').value;

                for(let i = 0; i < servings; i++){

                    const meal = {
                        // AUTO-GENERATED INPUTS
                        id: 1, // is this generated by the backend?
                        serving_id: 1, // is this generated by the backend?
                        cook: true, // switched to "false" when 'claimed' by 'consumer' user
                        eta: null, // will be altered later by the 'consumer' user
                        status: false, // 'false' = incomplete 'true' = complete
                        
                        // USER INPUTS
                        name: document.getElementById('name').value,
                        recipe: document.getElementById('recipe').value,
                        available: document.getElementById('available'),
                        category: document.getElementById('category').value,
                        add_info: document.getElementById('addInfo').value,
                    }

                    availableMeals.push(meal);
                }
            }
        }
    }
}